package starter.repository;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.junit4.SpringRunner;

import starter.data.entity.PhoneNumber;
import starter.types.PhoneType;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment=WebEnvironment.DEFINED_PORT)
public class PhoneNumberRepositoryTest {

  @Autowired
  private PhoneNumberRepository phoneNumberRepository;
  
  @Before
  public void doBefore() {
    PhoneNumber number = new PhoneNumber();
    number.setActiveFlag(true);
    number.setNumber("8018607615");
    number.setType(PhoneType.HOME);
    number = phoneNumberRepository.save(number);
    
    number.setNumber("8018607616");
    number.setType(PhoneType.MOBILE);
    phoneNumberRepository.save(number);
  }
  
  @Test
  public void testEmptyRecords() {
    assertThat(phoneNumberRepository.findAll()).isNotEmpty();
  }
  
  @Test
  public void testAutoGeneratedId() {
    PhoneNumber number = new PhoneNumber();
    number.setId(1);
    number.setActiveFlag(true);
    number.setNumber("8018607615");
    number.setType(PhoneType.OFFICE);
    number = phoneNumberRepository.save(number);
    assertThat(number.getId()).isNotEqualTo(1);
  }
}
